apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-analysis-app
spec:
  serviceAccountName: demo
  selector:
    matchLabels:
      app: code-analysis
  template:
    metadata:
      labels:
        app: code-analysis
    spec:
      containers:
        - name: main
          image: harbor-repo.vmware.com/tapsme/cartographer-code-analysis@sha256:5494be84aa98111799b7db82dc1e0cde8a205ef7ab8f93ec6a2d7b2a4aeb88fe
