apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-analysis
spec:
  serviceAccountName: demo
  selector:
    matchLabels:
      app: code-analysis
  template:
    metadata:
      labels:
        app: code-analysis
    spec:
      containers:
        - name: main
          image: harbor-repo.vmware.com/tapsme/cartographer-code-analysis@sha256:69e03b7a477f91bd257c2be6123cf859611284f7e03177e0ac5458d38760ec92
