apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-analysis
spec:
  serviceAccountName: demo
  selector:
    matchLabels:
      app: code-analysis
  template:
    metadata:
      labels:
        app: code-analysis
    spec:
      containers:
        - name: main
          image: harbor-repo.vmware.com/tapsme/cartographer-code-analysis@sha256:61aebc1031ff6c502bcaf7016754bd75e5a5738b127333623ecc069dc393a625
